baseURL: 'https://cgerull.github.io/techinfo'
languageCode: 'en-us'
title: 'techinfo.gerull.nl'
theme: 'hugo-theme-bootstrap4-blog'
menus:
  main:
    -  identifier: "home"
       name: "Home"
       url: "/posts/"
       weight: 10
    -  identifier: "about"
       name: "About"
       url: "/about/"
       weight: 80

