baseURL: 'https://techinfo.gerull.nl'
languageCode: 'en-us'
title: 'techinfo.gerull.nl'
theme: 'minimal'
params:
    author: "Claus Gerull"
    description: "Personal collection of IT recipies."
    githubUsername: "#"
    accent: "red"
menus:
  main:
    -  identifier: "home"
       name: "Home"
       url: "/posts/"
       weight: 10
    -  identifier: "about"
       name: "About"
       url: "/about/"
       weight: 80

